config/routes.rb
Spree::Core::Engine.add_routes do
	# Add your extension routes here
	namespace :admin, path: Spree.admin_path do
		resources :homes, only: [:index, :edit] do
			member do
				post 'publish'
			end
			collection do
				post 'home_items/update_order' => 'home_items#update_order'
			end	
			resources :home_items do
				post 'add' => 'home_items#add_third'
				post 'update'
				post 'add_product'
				post 'delete'
			end	
		end
	end	
	namespace :api, defaults: { format: 'json' } do
		namespace :v1 do
			get 'home' => 'home#index'
		end
	end			
end

app/models/spree/home.rb
module Spree
	class Home < Spree::Base
		acts_as_list

    validates :name, presence: true, uniqueness: { case_sensitive: false }

    has_many :home_items,  -> {order(position: :asc)}, inverse_of: :home
    has_one :root, -> { where parent_id: nil }, class_name: "Spree::HomeItem", dependent: :destroy

    after_create :set_root
    after_save :set_root_home_item_name

    default_scope { order("#{self.table_name}.position, #{self.table_name}.created_at") }

    private
      def set_root
        self.root ||= HomeItem.create!(home_id: id, name: name)
      end

      def set_root_home_item_name
        root.update_attributes(name: name)
      end
	end	
end

app/controllers/spree/admin/homes_controller.rb
module Spree
  module Admin
		class HomesController < ResourceController

			def edit
				@item_modules = Spree::HomeItem::ITEM_MODULES
				@parent_item = @home.root
				@items =  @parent_item.children.backend_items
				super
			end
			
			def publish
				#deleted 为false 的删除掉  active:为false deleted为true 为即将发布的 根据will_order 设置 position 

				home_item = Spree::HomeItem.find(params[:id])
				ActiveRecord::Base.transaction do
					descendants = home_item.descendants
					will_deleted = descendants.where(deleted: true)
					will_deleted.destroy_all

					will_active = descendants.where(deleted: false)
					will_active.each do|item|
						item.update!({active: true, position: item.will_order})
						if image = item.image
							unless image.active
								image.update!(active: true)
								Spree::HomeImage.where("home_item_id = ? and id != ?", item.id, image.id).destroy_all
							end	
						end	
					end	
				end
				
				render json: { status: true}
			end	
				
		end	
	end
end		

app/controllers/spree/api/v1/home_controller.rb
if defined? Spree::Api
	module Spree
		module Api
			module V1
				class HomeController < Spree::Api::BaseController
					skip_before_action :authenticate_user, only: [:index]
					skip_before_action :load_user, only: [:index]
					skip_before_action :load_user_roles, only: [:index]
					skip_before_action :authorize_for_order, only: [:index]
					
				
					def index
						@home_items = 	Spree::Home.find_by(name: 'APP')&.root&.children.frontend_items
					end
				end		
			end
		end
	end
end

app/views/spree/admin/homes/_list.html.erb
<table class="table" id='listing_taxonomies' data-hook>
  <thead>
    <tr data-hook="taxonomies_header">
      <th class="no-border"></th>
      <th><%= Spree.t(:name) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @homes.each do |home| %>
      <tr id="<%= spree_dom_id home %>" data-hook="homes_row">
        <td class="move-handle">
          <span class="icon icon-phone"></span>
        </td>
        <td><%= home.name %></td>
        <td class="actions actions-2 text-right">
          <%= link_to_edit home.id, no_text: true if can?(:edit, home) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/homes/_module.html.erb
<% @items.each do|item|%>
	<% if item.module_type == 1 %>
	<li class="list-group-item first clearfix" data-id="<%= item.id%>" data-position="<%= item.position%>"><div class="list-group-item-heading"><span class="icon icon-move"></span><div><%= item.name%></div><div><a href="<%=edit_admin_home_home_item_path(@home, item, :module_type =>1) %>"  class="btn btn-sm btn-primary"><%= I18n.t('home.edit')%></a><button type="button" class="btn btn-sm btn-danger module-delete" data-id="<%= item.id%>"><%= I18n.t('home.delete')%></button></div></div></li>
	<% elsif item.module_type == 2 %>
		<li class="list-group-item first clearfix" data-id="<%= item.id%>" data-position="<%= item.position%>"><div class="list-group-item-heading"><span class="icon icon-move"></span><div>Carousel</div><div><button class="btn btn-sm btn-success add-carousel" data-id="<%=item.id%>" data-homeid="<%= @home.id%>"><%= I18n.t('home.add')%></button><button type="button" class="btn btn-sm btn-danger module-delete" data-id="<%= item.id%>"><%= I18n.t('home.delete')%></button></div></div><div class="list-group-item-text">
				<% item.children.backend_items.each do|child| %>
				<div class="carousel" data-id="<%=child.id %>"><span class="icon icon-align-justify handle"></span><span><%= child.name %></span><a href="<%=edit_admin_home_home_item_path(@home, child, :module_type =>2) %>"  class="btn btn-sm btn-primary"><%= I18n.t('home.edit')%></a><button type="button" class="btn btn-sm btn-danger module-delete" data-id="<%= child.id%>"><%= I18n.t('home.delete')%></button></div>
				<% end %></div></li>
	<% elsif item.module_type == 3 %>
	<li class="list-group-item first clearfix" data-id="<%= item.id%>" data-position="<%= item.position%>"><div class="list-group-item-heading"><span class="icon icon-move"></span><div>Taxon</div><div><button type="button" class="btn btn-sm btn-danger module-delete" data-id="<%= item.id%>"><%= I18n.t('home.delete')%></button></div></div><div class="list-group-item-text">
				<% item.children.backend_items.each do|child| %>
				<div class="taxon" data-id="<%=child.id %>"><span class="icon icon-align-justify handle"></span><span><%= child.name %></span><a href="<%=edit_admin_home_home_item_path(@home, child, :module_type =>3) %>"  class="btn btn-sm btn-primary"><%= I18n.t('home.edit')%></a></div>
				<% end %></div></li>
	<% elsif item.module_type == 4 %>
	<li class="list-group-item first clearfix" data-id="<%= item.id%>" data-position="<%= item.position%>"><div class="list-group-item-heading"><span class="icon icon-move"></span><div><%= item.name%></div><div><a href="<%=edit_admin_home_home_item_path(@home, item, :module_type =>4) %>" class="btn btn-sm btn-primary"><%= I18n.t('home.edit')%></a><button type="button" class="btn btn-sm btn-danger module-delete" data-id="<%= item.id%>"><%= I18n.t('home.delete')%></button></div></div></li>
	<% elsif item.module_type == 5 %>
	<li class="list-group-item arrival clearfix" data-id="<%= item.id%>" data-position="<%= item.position%>"><div class="list-group-item-heading"><span></span><div>New Arrivals Feed<div>（Note：Every Time Loading 25 Products）</div></div><div><button type="button" class="btn btn-sm btn-danger module-delete" data-id="<%= item.id%>"><%= I18n.t('home.delete')%></button></div></div></li>
	<% end %>	
<% end %>	

app/views/spree/admin/homes/edit.html.erb
<div class="row" id="spree_home_edit">
	<div class="col-xs-12 col-md-3">
	<ul class="list-group" id="spree_item_modules">
		<li class="list-group-item active"><%= I18n.t('home.module') %></li>
		<% @item_modules.each do|k, v| %>
			<li class="list-group-item"><%= k.to_s.titleize %> <span class="icon icon-plus pull-right add-home-module" data-moduleid="<%= v %>"></span></li>
		<% end %>	
	</ul>
	</div>
	<div class="col-xs-12 col-md-9" id="spree_home_item_content">
		<ul class="list-group" id="spree_home_item_list">
			<li class="list-group-item active clearfix"><%= @home.name %> Index <button class="btn btn-success pull-right" id="publish" data-homeid="<%= params[:id]%>"><%= I18n.t('home.publish')%></button></li>
			<%= render 'module' %>
		</ul>	
	</div>
</div>
<script>
	home_setup('<%= @home.id%>', '<%= @parent_item.id%>')
</script>

app/views/spree/admin/homes/index.html.erb
<% content_for :page_title do %>
  <%= I18n.t('home_menu') %>
<% end %>


<% if @homes.any? %>
  <div id="list-taxonomies" data-hook>
    <%= render 'list' %>
  </div>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Home)) %>,
  </div>
<% end %>